---

- name: Create Postgresql role
  become_user: postgres
  postgresql_user: name={{ dbuser }} password={{ dbpassword }} role_attr_flags=CREATEDB,NOSUPERUSER,LOGIN

- name: Create Postgresql DB
  become_user: postgres
  postgresql_db: name={{ dbname }} encoding='UTF-8' owner={{ dbuser }}
