---

- name: add passenger pepo
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x561F9B9CAC40B2F7 state=present

- name: install packages https 
  action: apt pkg={{item}} state=installed update_cache=true
  with_items:
    - apt-transport-https
    - ca-certificates

- name: add phusion passanger repo
  apt_repository: repo='deb https://oss-binaries.phusionpassenger.com/apt/passenger trusty main'

-name: update
 apt: update_cache=yes

- name: install nginx-extras and passanger
  action: apt pkg={{ item }} state=installed update_cache=true
  with_items:
    # note: Passenger repo has it's own nginx-extras package.
    - nginx-extras
    - passenger

- name: Ensure passenger_root is set
  lineinfile:
    dest=/etc/nginx/nginx.conf
    state=present
    backup=yes
    regexp='#?\s*passenger_root /usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini;'
    line='passenger_root /usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini;'

- name: Ensure passenger_ruby is set
  lineinfile:
    dest=/etc/nginx/nginx.conf
    state=present
    backup=yes
    backrefs=yes
    regexp='#?\s*passenger_ruby /usr/bin/passenger_free_ruby;'
    line='passenger_ruby /usr/bin/passenger_free_ruby;'



- name: remove default nginx conf
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: remove old app symlink if exist
  file:  path=/etc/nginx/sites-enabled/{{ app_name }} state=absent

- name: copy configure nginx
  template: src= nginx.conf.j2 dest=/etc/nginx/sites-available/{{ app_name }} group=www-data owner=www-data force=yes

- name: enable the app
  file: src=/etc/nginx/sites-available/{{ app_name }} dest=/etc/nginx/sites-enabled/{{ app_name }} state=link owner=www-data group-www-data force=yes


- name: restart nginx
  action: service name=nginx state=restarted

